on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.6'
    - run: |
        go build std
