on:
  push:
    branches: [ "main" ]

jobs:
  build-amd64:
    runs-on: ubuntu-22.04
    env: 
      GOARCH: amd64
    steps:
    - uses: actions/checkout@v3
      with:
        repository: hashicorp/consul
        ref: "v1.16.0"
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.6'
    - run: |
        go build .